const data = {
  videos: [
    {
      videoName: 'videoSatu',
      genre: ['Action', 'Comedy'],
      production: { company: 'Pixar', producer: 'Jakcson', year: 2020 },
      description: 'film aksi satu',
      rating: 1.5,
      price: 10,
      image: 'namaImage.jpg',
      url: 'http://localhost:3002/assets/namaImage.jpg',
    },
    {
      videoName: 'videoDua',
      genre: ['Action', 'Comedy'],
      production: { company: 'Pixar', producer: 'Jakcson', year: 2020 },
      description: 'film aksi dua',
      rating: 2.5,
      price: 10,
      image: 'namaImage.jpg',
      url: 'http://localhost:3002/assets/namaImage.jpg',
    },
    {
      videoName: 'videoTiga',
      genre: ['Action', 'Comedy'],
      production: { company: 'Pixar', producer: 'Jakcson', year: 2020 },
      description: 'film aksi tiga',
      rating: 3.5,
      price: 15,
      image: 'namaImage.jpg',
      url: 'http://localhost:3002/assets/namaImage.jpg',
    },
    {
      videoName: 'videoEmpat',
      genre: ['Action', 'Comedy'],
      production: { company: 'Pixar', producer: 'Jakcson', year: 2021 },
      description: 'film aksi empat',
      rating: 4.5,
      price: 20,
      image: 'namaImage.jpg',
      url: 'http://localhost:3002/assets/namaImage.jpg',
    },
    {
      videoName: 'videoLima',
      genre: ['Action', 'Comedy'],
      production: { company: 'Pixar', producer: 'Jakcson', year: 2021 },
      description: 'film aksi lima',
      rating: 5.5,
      price: 25,
      image: 'namaImage.jpg',
      url: 'http://localhost:3002/assets/namaImage.jpg',
    },
    {
      videoName: 'videoEnam',
      genre: ['Action', 'Comedy'],
      production: { company: 'Pixar', producer: 'Jakcson', year: 2021 },
      description: 'film aksi enam',
      rating: 6.5,
      price: 30,
      image: 'namaImage.jpg',
      url: 'http://localhost:3002/assets/namaImage.jpg',
    },
    {
      videoName: 'videoTujuh',
      genre: ['Action', 'Comedy'],
      production: { company: 'Pixar', producer: 'Jakcson', year: 2022 },
      description: 'film aksi tujuh',
      rating: 7.5,
      price: 35,
      image: 'namaImage.jpg',
      url: 'http://localhost:3002/assets/namaImage.jpg',
    },
    {
      videoName: 'videoDelapan',
      genre: ['Action', 'Comedy'],
      production: { company: 'Pixar', producer: 'Jakcson', year: 2022 },
      description: 'film aksi delapan',
      rating: 8.5,
      price: 40,
      image: 'namaImage.jpg',
      url: 'http://localhost:3002/assets/namaImage.jpg',
    },
    {
      videoName: 'videoSembilan',
      genre: ['Action', 'Comedy'],
      production: { company: 'Pixar', producer: 'Jakcson', year: 2022 },
      description: 'film aksi sembilan',
      rating: 9.5,
      price: 45,
      image: 'namaImage.jpg',
      url: 'http://localhost:3002/assets/namaImage.jpg',
    },
    {
      videoName: 'videoSepuluh',
      genre: ['Action', 'Comedy'],
      production: { company: 'Pixar', producer: 'Jakcson', year: 2023 },
      description: 'film aksi sepuluh',
      rating: 10.5,
      price: 50,
      image: 'namaImage.jpg',
      url: 'http://localhost:3002/assets/namaImage.jpg',
    },
  ],
};
export default data;
